name: Build qmk_javonca

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/qmk/qmk_firmware.git
  REPO_BRANCH: master
  QMK_CONFIG: xinput
  UPLOAD_RELEASE: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Clone QMK fork
      run: | 
        git clone $REPO_URL -b $REPO_BRANCH ./qmk_firmware
        
    - name: Set Up QMK
      working-directory: ./qmk_firmware
      run: |
        qmk setup -y
        
    - name: Copy keymap
      run: |
        mkdir -p qmk_firmware/keyboards/
        cp -rup ./qmk/* ./qmk_firmware/keyboards/
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Compile Custom Firmware
      working-directory: ./qmk_firmware
      run: |
        qmk compile -kb javonca/$QMK_CONFIG -km default
        
    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload compiled firmware (build artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Firmware Files
        path: |
          ./qmk_firmware/*.hex
          ./qmk_firmware/*.bin

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        files: |
          ./qmk_firmware/*.hex
          ./qmk_firmware/*.bin
     
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
